data:
  train_dir: "multimodal-data/fashion_dataset_subset/images/train"
  train_ann: "multimodal-data/fashion_dataset_subset/train_annotations.csv"
  val_dir: "multimodal-data/fashion_dataset_subset/images/val"
  val_ann: "multimodal-data/fashion_dataset_subset/val_annotations.csv"
  batch_size: 4
  num_workers: 8

model:
  config_path: "groundingdino/config/GroundingDINO_SwinT_OGC.py"
  weights_path: "weights/groundingdino_swint_ogc.pth"

training:
  num_epochs: 200
  learning_rate: 1e-4
  save_dir: "weights"
  save_frequency: 5
  warmup_epochs: 5
  use_lora: true
  use_lora_layers: true # This applies lora to only bbox pred layer and few transformer decoder layers the number of trainable parameters in this case will be < 1% of total parameters
                        # if it is false then it applies 
  visualization_frequency: 5